name: Build and Release Extension

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      -  uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache-dependency-path: ./package-lock.json
          node-version: 20.x
          cache: npm

      - working-directory: ./
        run: npm i

      - working-directory: ./
        run: npm install -g @vscode/vsce

      - working-directory: ./
        run: vsce package

      - run: echo "VSIX_NAME=$(ls *.vsix)" >> $GITHUB_ENV

      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: latest
          draft: false
          prerelease: false

      - uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: "abstract-language-support.vsce"
          asset_content_type: extension/vsce
          asset_path: ${{ env.VSIX_NAME }}
