name: Build and Release Extension

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: ./package-lock.json

      - run: npm ci

      - run: npm install -g @vscode/vsce

      - run: vsce package

      - uses: softprops/action-gh-release@v1
        with:
          name:  latest
          tag_name: latest
          draft: false
          prerelease: false
          files: '*.vsce'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
